"""Add author column to content table

Revision ID: 5b738263c9fd
Revises: 3e3fcad7b08f
Create Date: 2024-02-19 22:52:02.105451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b738263c9fd'
down_revision = '3e3fcad7b08f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.drop_column('author')

    # ### end Alembic commands ###
